name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 64000
          script: |
            cd /home/jejakode/laravel/kubah/
            git pull
            composer_install
            php artisan_optimize
            npm_install
            npm_run_build

      # - name: Clean up
      #   run: |
      #     rm -rf node_modules
      #     composer clear-cache

  composer_install:
    name: Composer Install
    run: composer install

  php artisan_optimize:
    name: PHP Artisan Optimize
    run: php artisan optimize

  npm_install:
    name: NPM Install
    run: npm install

  npm_run_build:
    name: NPM Run Build
    run: npm run build
